apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: wilbert201112058/backend:latest
        ports:
        - containerPort: 8080
